In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5]
array=np.array(a)
array

array([1, 2, 3, 4, 5])

In [4]:
aray=np.array([1,2,3,4,5])
aray

array([1, 2, 3, 4, 5])

In [ ]:
a = int(input())
array = np.array(list(map(int, str(input()).split())))
print(array)

In [5]:
arr = []
a = int(input())
for j in range(a):
    value = int(input())
    arr.append(value)
arr

3
1
2
3


[1, 2, 3]

In [ ]:
                            ## Two dimentional Array
ar = np.array([[1.3,2.5,3.3,4.2],[2.5,3.8,4.9,5.1]])
print(ar)

In [27]:
ar[1,3]

5.1

In [28]:
## get dimention
ar.ndim            ##(ndim = no of dimention)

2

In [29]:
array.ndim

1

In [30]:
## get shape
ar.shape          ## will be print how many row and column

(2, 4)

In [31]:
array.shape

(5,)

In [32]:
ar.size

8

In [33]:
ar.dtype

dtype('float64')

In [34]:
ar.itemsize

8

In [35]:
ar.nbytes

64

In [36]:
                                   ## 3 dimention array
    
    

b = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
b

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [37]:
b[0,1,3]

9

## Matrix

In [38]:
np.zeros((3,3), dtype = 'int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
x = np.ones((3,3),dtype='int32')
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
x[2,1] = 4
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 4, 1]])

In [41]:
x.shape

(3, 3)

In [42]:
x.size

9

In [43]:
x.itemsize

4

In [6]:
y = {}
for j in range(3):
    for i in range(3):
        x = int(input())
        y[j,i] = x
        
print(y)

1
2
3
4
5
6
7
89
9
{(0, 0): 1, (0, 1): 2, (0, 2): 3, (1, 0): 4, (1, 1): 5, (1, 2): 6, (2, 0): 7, (2, 1): 89, (2, 2): 9}


In [45]:
                                       ## filling up matrix with any value
x = np.full((3,3),(5))
x

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
for j in range(3):
    for i in range(3):
        t = int(input())
        x[j,i] = t
        
print(x)

5


TypeError: 'int' object does not support item assignment

## x

In [48]:
## creating random matrix
z = np.random.rand(3,3)
z

array([[0.67942152, 0.64484669, 0.81512226],
       [0.73232886, 0.06756983, 0.31756522],
       [0.31315268, 0.30739936, 0.71977236]])

## creating random intiger array


In [49]:
np.random.randint(14, size = (3,3))

array([[ 7, 10,  8],
       [ 4, 12, 11],
       [ 2, 13,  1]])

## creating identity matrix


In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Mathematics

In [51]:
z = np.array([1,2,3,4])
print(z)

[1 2 3 4]


In [52]:
z+1

array([2, 3, 4, 5])

In [53]:
z-1

array([0, 1, 2, 3])

In [54]:
z*3

array([ 3,  6,  9, 12])

In [55]:
z/2

array([0.5, 1. , 1.5, 2. ])

In [56]:
np.sum(z)

10

In [57]:
np.min(z)

1

In [58]:
np.max(z)

4

In [59]:
np.cos(z)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [60]:
np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [61]:
np.mean(z)

2.5